Repository SFDO-Tooling/MetaDeploy, pull requests merged in 2019-05, with the labels that each got.

#258 [install-logs] Show logs as they come in
  .eslintrc.yml
  flow-typed/npm/@salesforce/design-system-react_vx.x.x.js
  flow-typed/npm/i18next-browser-languagedetector_vx.x.x.js
  flow-typed/npm/i18next-xhr-backend_vx.x.x.js
  flow-typed/npm/i18next_vx.x.x.js
  flow-typed/npm/react-document-title_vx.x.x.js
  flow-typed/npm/react-i18next_vx.x.x.js
  flow-typed/npm/react-router-dom_v5.x.x.js
  flow-typed/npm/redux-logger_vx.x.x.js
  flow-typed/npm/redux-thunk_vx.x.x.js
  flow-typed/npm/redux_v4.x.x.js
  flow-typed/npm/sockette_vx.x.x.js
  locales/en/translation.json
  locales_dev/en/translation.json
  metadeploy/api/flows.py
  metadeploy/api/management/commands/populate_data.py
  metadeploy/api/result_spool_logger.py
  metadeploy/api/serializers.py
  metadeploy/api/tests/flows.py
  metadeploy/api/tests/jobs.py
  metadeploy/api/tests/result_spool_logger.py
  metadeploy/api/tests/serializers.py
  package.json
  src/js/components/header/customDomainModal.js
  src/js/components/header/index.js
  src/js/components/header/login.js
  src/js/components/jobs/detail.js
  src/js/components/jobs/progressBar.js
  src/js/components/jobs/shareModal.js
  src/js/components/plans/clickThroughAgreementModal.js
  src/js/components/plans/detail.js
  src/js/components/plans/header.js
  src/js/components/plans/preflightResults.js
  src/js/components/plans/preflightWarningModal.js
  src/js/components/plans/stepsTable/index.js
  src/js/components/plans/stepsTable/installDataCell.js
  src/js/components/plans/stepsTable/kindDataCell.js
  src/js/components/plans/stepsTable/nameDataCell.js
  src/js/components/plans/stepsTable/requiredDataCell.js
  src/js/components/plans/stepsTable/toggleLogsDataColumnLabel.js
  src/js/components/plans/userInfo.js
  src/js/components/products/header.js
  src/js/store/jobs/reducer.js
  src/js/store/plans/reducer.js
  src/sass/components/_header.scss
  src/sass/components/_steps.scss
  src/sass/config/_z-index.scss
  src/sass/patterns/_containers.scss
  test/js/components/jobs/detail.test.js
  test/js/components/jobs/progressBar.test.js
  test/js/components/jobs/shareModal.test.js
  test/js/components/plans/ctaButton.test.js
  test/js/components/plans/detail.test.js
  test/js/components/plans/preflightResults.test.js
  test/js/components/plans/preflightWarningModal.test.js
  test/js/components/plans/stepsTable.test.js
  test/js/components/products/list.test.js
  yarn.lock
Labels: ready for review

#265 [long-install] Add average time to plans
  config/settings/base.py
  locales/en/translation.json
  locales_dev/en/translation.json
  metadeploy/api/jobs.py
  metadeploy/api/migrations/0065_job_success_at.py
  metadeploy/api/migrations/0072_merge_20190504_1506.py
  metadeploy/api/models.py
  metadeploy/api/serializers.py
  metadeploy/api/tests/models.py
  metadeploy/api/tests/serializers.py
  metadeploy/api/tests/views.py
  src/js/components/header/index.js
  src/js/components/jobs/currentJobAlert.js
  src/js/components/jobs/detail.js
  src/js/components/plans/detail.js
  src/js/components/plans/intro.js
  src/js/store/org/reducer.js
  src/js/store/plans/reducer.js
  src/js/utils/dates.js
  src/sass/components/_alerts.scss
  src/sass/components/_manifest.scss
  src/sass/components/_offlineAlert.scss
  test/js/components/header/index.test.js
  test/js/components/jobs/currentJobAlert.test.js
  test/js/components/jobs/detail.test.js
  test/js/components/plans/detail.test.js
  test/js/utils/dates.test.js
Labels: ready for review

#314 [improve-average-duration] Use median for "average duration"
  config/settings/base.py
  metadeploy/api/models.py
Labels: enhancement, ready for review

#315 [realistic-plan] Add EDA to sample data
  metadeploy/api/management/commands/populate_data.py
  metadeploy/api/management/commands/tests/populate_data.py
Labels: ready for review

#312 [post-logs-styles] Simplify styles from install-logs branch
  src/sass/components/_steps.scss
Labels: wip

#316 [hotfix-api-error] Anticipate possible `null` API response.
  src/js/store/jobs/actions.js
  src/js/store/plans/actions.js
  test/js/store/jobs/actions.test.js
Labels: ready for review

#324 [change-preflight-shape] Handle the new shape of Preflight results
  metadeploy/api/jobs.py
  metadeploy/api/models.py
  metadeploy/api/serializers.py
  metadeploy/api/tests/serializers.py
  src/js/components/plans/ctaButton.js
  src/js/components/plans/preflightWarningModal.js
  src/js/components/plans/stepsTable/nameDataCell.js
  test/js/components/plans/ctaButton.test.js
  test/js/components/plans/preflightWarningModal.test.js
Labels: ready for review

#313 [fetch-plans] Fetch plans on-demand.
  .flowconfig
  docs/api/products.rst
  docs/api/versions.rst
  jest.config.js
  metadeploy/api/filters.py
  metadeploy/api/serializers.py
  metadeploy/api/tests/views.py
  metadeploy/api/views.py
  package.json
  src/js/components/plans/detail.js
  src/js/components/products/detail.js
  src/js/components/utils.js
  src/js/store/plans/actions.js
  src/js/store/plans/reducer.js
  src/js/store/plans/selectors.js
  src/js/store/products/actions.js
  src/js/store/products/reducer.js
  src/js/store/products/selectors.js
  test/js/components/jobs/detail.test.js
  test/js/components/plans/detail.test.js
  test/js/components/products/detail.test.js
  test/js/components/products/list.test.js
  test/js/components/products/listItem.test.js
  test/js/components/utils.test.js
  test/js/setupTests.js
  test/js/store/products/actions.test.js
  test/js/store/products/reducer.test.js
  yarn.lock
Labels: ready for review

#328 [installation-banner] Do not show "Installation currently running" banner on currently-running installation page.
  package.json
  src/js/components/404.js
  src/js/components/authError.js
  src/js/components/header/index.js
  src/js/components/jobs/currentJobAlert.js
  src/js/components/jobs/detail.js
  src/js/components/plans/detail.js
  src/js/components/products/detail.js
  src/js/components/products/list.js
  src/js/index.js
  test/js/components/404.test.js
  test/js/components/jobs/currentJobAlert.test.js
  test/js/components/jobs/detail.test.js
  test/js/components/utils.test.js
  yarn.lock
Labels: ready for review

#329 [resolve-warning] Make preflight warnings clearer.
  locales/en/translation.json
  locales_dev/en/translation.json
  src/js/components/plans/ctaButton.js
  src/js/components/plans/stepsTable/index.js
  src/js/components/plans/stepsTable/nameDataCell.js
  test/js/components/plans/ctaButton.test.js
Labels: ready for review

#333 [average-time-note] 🛢 Show disclaimer tooltip with average-install-time for production orgs.
  locales/en/translation.json
  locales_dev/en/translation.json
  metadeploy/api/admin.py
  metadeploy/api/migrations/0075_job_full_org_type.py
  metadeploy/api/models.py
  metadeploy/api/serializers.py
  metadeploy/api/tests/templatetags_api_bootstrap.py
  metadeploy/api/tests/views.py
  src/js/components/jobs/detail.js
  src/js/components/plans/detail.js
  src/js/components/plans/intro.js
  src/js/store/jobs/reducer.js
  src/js/store/user/reducer.js
  test/js/components/jobs/detail.test.js
Labels: ready for review

#307 [ansi-colors] Colorize logs
  metadeploy/api/flows.py
  metadeploy/api/result_spool_logger.py
  metadeploy/api/tests/result_spool_logger.py
  requirements/base.txt
  src/js/components/plans/stepsTable/nameDataCell.js
Labels: ready for review

#330 [product-tab-link] Link directly to a product-category tab.
  src/js/components/products/list.js
  src/js/utils/helpers.js
  test/js/components/products/list.test.js
Labels: ready for review
